spring:
  couchbase:
    bootstrap-hosts: 127.0.0.1:8091
    bucket:
      name: Default
      password: Default
    username: Administrator
    password: Administrator
  data:
    couchbase:
      auto-index: true
